### ISSUE TITLE
Data loss when docker is restarted

### ISSUE THREAD

**Issue by tranduyhung** [wekan/wekan-mongodb#9]
I installed successfully, registered and was using Wekan with no problems. However, if docker is stopped and started by any reasons (server restart, manual stop-start or restart), the database is empty, all users are lost

````
$ sudo docker exec -it wekan-db bash
root@31dbdabb9ade:/# mongo
MongoDB shell version: 3.2.19
connecting to: test
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
> show dbs
local  0.000GB
wekan  0.000GB
> use wekan
switched to db wekan
> db.users.find()
> 
````

Do you have any suggestions to trace this problem and fix it? Thanks!

**Comment by xet7** [comment]
Recommended way to install:
https://github.com/wekan/wekan-snap/wiki/Install

About backup, restore, and related issues:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

What docker-compose.yml file you used? Did you use latest quay image?

**Comment by xet7** [comment]
This looks too much like previous issue today #8

I don't know what really is broken. I did add newer version of MongoDB to that docker-compose.yml file, I don't know could that be the reason.

Also Docker Hub images have been broken many times.

Anyway, I'll add warning to releases page that Docker is dangerous and eats all your data, make backup now, and uninstall it.

**Comment by xet7** [comment]
I will change to use previous MongoDB version 3.2.18.

**Comment by tranduyhung** [comment]
Thank you @xet7 for the info. This is a brand new installation of Wekan, there is no needs for importing or exporting database. I have tried MongoDB 3.2.18 but the problem still exists. I will try a different method to Docker.

**Comment by capi** [comment]
I am currently still using the Docker image and it's not using data. I'm using `bind` mounts instead of volumes, maybe this makes it working?
Basically, my modified version of the `docker-compose.yml` is:

```
  wekandb:
    image: mongo:3.2
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /data/wekan/db/:/data/db
      - /data/wekan/dump/:/dump
```
